[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "hello_world"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    'timefold == 1.16.0b0',
    'pydantic == 2.7.3'
]


[project.scripts]
run-app = "hello_world:main"
